version: '3.8'

services:
  evolvefit:
    build: .
    container_name: evolvefit-app
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"
      - "traefik.http.routers.evolvefit.service=evolvefit"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - evolvefit

networks:
  evolvefit:
    driver: bridge