version: '3.8'

services:
  evolvefit:
    build: .
    container_name: evolvefit-app
    restart: unless-stopped
    networks:
      - evolvefit
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      
      # Configuração do roteador
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=web,websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      
      # Configuração do serviço
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"
      
      # Middleware de segurança
      - "traefik.http.routers.evolvefit.middlewares=security-headers@docker"
      - "traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-For=$$remote_addr"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      
      # Redirecionamento HTTP para HTTPS
      - "traefik.http.routers.evolvefit-http.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit-http.entrypoints=web"
      - "traefik.http.routers.evolvefit-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  evolvefit:
    external: true
    name: evolvefit