version: '3.8'

services:
  evolvefit:
    image: nginx:alpine
    container_name: evolvefit-app
    restart: unless-stopped
    networks:
      - evolvefit
    command: >
      sh -c "apk add --no-cache git &&
             rm -rf /tmp/evolvefit &&
             git clone https://github.com/abdoufbello/evolvefit.git /tmp/evolvefit &&
             cp -r /tmp/evolvefit/* /usr/share/nginx/html/ &&
             rm -rf /etc/nginx/conf.d/* &&
             cp /tmp/evolvefit/nginx.conf /etc/nginx/nginx.conf &&
             nginx -t &&
             nginx -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"
      - "traefik.http.routers.evolvefit.service=evolvefit"

networks:
  evolvefit:
    external: true