version: '3.8'

services:
  evolvefit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evolvefit
    restart: unless-stopped
    networks:
      - evolvefit
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=evolvefit"
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=web,websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"
    environment:
      - NODE_ENV=production
      - APP_NAME=EvolveFit
      - APP_VERSION=1.0.0
      - APP_DOMAIN=evolvefit.leplustudio.top
      - N8N_LLM_WEBHOOK_URL=https://n8n.leplustudio.top/webhook/evolvefit-llm
      - N8N_NOTION_WEBHOOK_URL=https://n8n.leplustudio.top/webhook/evolvefit-notion
      - N8N_ANALYSIS_WEBHOOK_URL=https://n8n.leplustudio.top/webhook/evolvefit-analysis
      - LLM_MODEL=gpt-4-turbo
      - SYNC_INTERVAL_MINUTES=30
      - DEBUG_MODE=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  evolvefit:
    external: true