version: '3.8'

services:
  evolvefit:
    image: httpd:alpine
    container_name: evolvefit-app
    restart: unless-stopped
    networks:
      - evolvefit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=web,websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"

networks:
  evolvefit:
    external: true