version: '3.8'

services:
  evolvefit:
    image: nginx:alpine
    container_name: evolvefit-app
    restart: unless-stopped
    networks:
      - evolvefit
    command: >
      sh -c "rm -rf /etc/nginx/conf.d/* &&
             wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/abdoufbello/evolvefit/main/index.html &&
             wget -O /usr/share/nginx/html/config.js https://raw.githubusercontent.com/abdoufbello/evolvefit/main/config.js &&
             wget -O /usr/share/nginx/html/test.html https://raw.githubusercontent.com/abdoufbello/evolvefit/main/test.html &&
             wget -O /tmp/nginx.conf https://raw.githubusercontent.com/abdoufbello/evolvefit/main/nginx.conf &&
             nginx -t -c /tmp/nginx.conf &&
             nginx -c /tmp/nginx.conf -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolvefit.rule=Host(`evolvefit.leplustudio.top`)"
      - "traefik.http.routers.evolvefit.entrypoints=websecure"
      - "traefik.http.routers.evolvefit.tls=true"
      - "traefik.http.routers.evolvefit.tls.certresolver=leresolver"
      - "traefik.http.services.evolvefit.loadbalancer.server.port=80"
      - "traefik.http.routers.evolvefit.service=evolvefit"

networks:
  evolvefit:
    external: true